name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  # Every Sunday at 11:00am UTC
  schedule:
    - cron: '0 11 * * 0'

jobs:
  ci:
    name: CI
    # Only run cron on the silverstripe account
    if: (github.event_name == 'schedule' && startsWith(github.repository, 'silverstripe/')) || (github.event_name != 'schedule')
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
